# <span style="color:blue">  Tutorial 6, Question 5: </span>

Given the training data:
{𝑥 = −1} → { 𝑦 = 𝑐𝑙𝑎𝑠𝑠1 }
{𝑥 = 0 } → { 𝑦 = 𝑐𝑙𝑎𝑠𝑠1 }
{𝑥 = 0.5} → { 𝑦 = 𝑐𝑙𝑎𝑠𝑠2 }
{𝑥 = 0.3} → { 𝑦 = 𝑐𝑙𝑎𝑠𝑠3 }
{𝑥 = 0.8} → { 𝑦 = 𝑐𝑙𝑎𝑠𝑠2 }

1. Predict the class label for {𝑥 = −0.1} and {𝑥 = 0.4} based on linear regression towards a one-hot encoded
target.
2. Predict the class label for {𝑥 = −0.1} and {𝑥 = 0.4} using a polynomial model of 5th order and a one-hot
encoded target.

In [2]:
import numpy as np 
from numpy.linalg import inv 
from sklearn.preprocessing import PolynomialFeatures 

X = np.array([[1,-1], [1,0], [1,0.5], [1,0.3], [1,0.8]]) 
Y = np.array([[1,0,0], [1,0,0], [0,1,0], [0,0,1], [0,1,0]]) 

## Linear regression for classification 
W = inv(X.T @ X) @ X.T @ Y 
print(W) 

Xt = np.array([[1,-0.1], [1,0.4]]) 
y_predict = Xt @ W 
print(y_predict) 
y_class_predict = [[1 if y == max(x) else 0 for y in x] for x in y_predict ] 
print(y_class_predict) 

## Polynomial regression for 
## Generate polynomial features 
order = 5 
poly = PolynomialFeatures(order) 

## only the data column (2nd) is needed for generation of polynomial terms 
reshaped = X[:,1].reshape(len(X[:,1]),1) 
P = poly.fit_transform(reshaped) 
reshaped = Xt[:,1].reshape(len(Xt[:,1]),1) 
Pt = poly.fit_transform(reshaped) 

## dual solution (without ridge) 
Wp_dual = P.T @ inv(P @ P.T) @ Y 
print(Wp_dual) 

yp_predict = Pt @ Wp_dual 
print(yp_predict) 
yp_class_predict = [[1 if y == max(x) else 0 for y in x] for x in yp_predict ] 

print(yp_class_predict)

None
[[ 0.07441524  1.53840883 -0.61282406]
 [ 0.10300392 -0.0500674  -0.05293652]
 [ 0.21274711 -0.40080364  0.18805654]
 [-0.2510306   0.23622893  0.01480167]
 [-0.0365881  -0.50708077  0.54366887]]
[[0, 0, 1], [0, 1, 0], [1, 0, 0], [0, 0, 1], [1, 0, 0], [0, 0, 1], [1, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 0, 1], [0, 1, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 0, 0], [0, 0, 1], [0, 0, 1], [1, 0, 0], [1, 0, 0], [0, 0, 1], [1, 0, 0], [1, 0, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [0, 0, 1], [0, 0, 1], [1, 0, 0], [0, 0, 1], [0, 0, 1], [0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 1.]
 [0. 1. 1.]
 [0. 0. 0.]
 [0. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0